### ISSUE TITLE
Request Feature

### ISSUE THREAD

**Issue by jorea143** [Freenex1911/FeexRanks#1]
Is possible to add a feature where the Rank name will be added as a prefix to player name? This way players can brag or be proud of his/her ranking.

Thanks.

**Comment by takahashitakeshi** [comment]
hello and excuse me, sir.. I am a fan of your plugin. This plugin is very good with server unturned but something happened in my server.
First, i don't know the name of column in database MySQL. So i create a database liked your feexhitman plugin.. different bounty and points.
Second, when i played in my server, i had 1000 points but when i loged out and loged in again, my point was reset. Can you fix that?
Please tell me the name of column and fix save the point.
Thank you very much.

**Comment by takahashitakeshi** [comment]
I have 1 problem too. I reach the lv and unlock the kit name. But I can use that kit in kit command. Pls fix it

**Comment by Pustalorc** [comment]
@takahashitakeshi The second problem simply is because when you reach a level, the kit ISN'T UNLOCKED. FeexRanks simply just gives the kit to the player that leveled up and that's it. In other words, that your problem is not a problem, it's a misunderstanding.

And going back to your first problem, it would be very appreciated if you could post more details, as it just looks like the database simply didn't register the points/save them. It could also be that if the database is hosted elsewhere, someone changed the tables or even deleted the database.

**Comment by takahashitakeshi** [comment]
Ok! I mean. When i use your plugin on my server. When i reach a high rank
and over 1000 points. I disconnect and when i login again. My point is
reset.. I have 0 point and no ranks. My database create a new row with my
name and my steamid

2016-09-16 2:19 GMT+07:00 persiafighter notifications@github.com:

**Comment by Pustalorc** [comment]
@takahashitakeshi The plugin is supposed to create a new row every time a COMPLETELY NEW player joins, so if it is doing that, either it is not reading the table correctly, or there is something up with your config.

**Comment by takahashitakeshi** [comment]
No.. I mean. I am old member in my server. When i rejoin to my server. I
have a new row and 0 point. Before i had 1000 points (old row)

2016-09-16 22:25 GMT+07:00 persiafighter notifications@github.com:

**Comment by Pustalorc** [comment]
@takahashitakeshi Alright, I kind of understand now. Could you post server logs or something that could give me a visual so that I can try to see if its something with the config?
